'\" t
.\"     Title: ncrack
.\"    Author: [see the "Authors" section]
.\" Generator: DocBook XSL Stylesheets v1.75.1 <http://docbook.sf.net/>
.\"      Date: 08/01/2009
.\"    Manual: Ncrack Reference Guide
.\"    Source: Ncrack
.\"  Language: English
.\"
.TH "NCRACK" "1" "08/01/2009" "Ncrack" "Ncrack Reference Guide"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ncrack \- Network authentication cracking tool
.SH "SYNOPSIS"
.HP \w'\fBncrack\fR\ 'u
\fBncrack\fR [\fIOptions\fR] {\fItarget\ specification\fR}
.SH "DESCRIPTION"
.\" Ncrack: description of
.PP
Ncrack is an open source tool for network authentication cracking\&. It was designed for high\-speed parallel cracking using a dynamic engine that can adapt to different network situations\&. Ncrack can also be extensively fine\-tuned for special cases, though the default parameters are generic enough to cover almost every situation\&. It is built on a modular architecture that allows for easy extension to support additional protocols\&. While Ncrack\'s main purpose is to audit the security of large networks for default, weak passwords in a rapid, yet reliable way, it can also be used to conduct some fairly sophisticated bruteforcing attacks\&.
.PP
The output from Ncrack is a list of found credentials, if any, for each of the targets specified\&. Ncrack can also print an interactive status report of progress so far and possibly additional debugging information that can help track problems, if the user selected that option\&.
.PP
A typical Ncrack scan is shown in
Example\ \&1\&. The only Ncrack arguments used in this example are the two target IP addresses along with the the corresponding ports for each of them\&. The two example ports 21 and 22 are automatically resolved to the default services listening on them: ftp and ssh\&.
.PP
\fBExample\ \&1.\ \&A representative Ncrack scan\fR
.\" -v: example of
.sp
.if n \{\
.RS 4
.\}
.nf

$ ncrack 10\&.0\&.0\&.130:21 192\&.168\&.1\&.2:22

Starting Ncrack 0\&.01ALPHA ( http://ncrack\&.org ) at 2009\-07\-24 23:05 EEST

Discovered credentials for ftp on 10\&.0\&.0\&.130 21/tcp:
10\&.0\&.0\&.130 21/tcp ftp: admin hello1
Discovered credentials for ssh on 192\&.168\&.1\&.2 22/tcp:
192\&.168\&.1\&.2 22/tcp ssh: guest 12345
192\&.168\&.1\&.2 22/tcp ssh: admin money$

Ncrack done: 2 services scanned in 156\&.03 seconds\&.

Ncrack finished\&.

    
.fi
.if n \{\
.RE
.\}
.PP
The latest version of Ncrack can be obtained from
\m[blue]\fB\%http://ncrack.org\fR\m[]\&. The latest version of this man page is available at http://ncrack\&.org/man\&.html \&.
.SH "OPTIONS SUMMARY"
.PP
This options summary is printed when Ncrack is run with no arguments\&. It helps people remember the most common options, but is no substitute for the in\-depth documentation in the rest of this manual\&.
.\" summary of options
.\" command-line options: of Ncrack
.sp
.if n \{\
.RS 4
.\}
.nf
Ncrack 0\&.01ALPHA ( http://ncrack\&.org )
Usage: ncrack [Options] {target specification}
TARGET SPECIFICATION:
  Can pass hostnames, IP addresses, networks, etc\&.
  Ex: scanme\&.nmap\&.org, microsoft\&.com/24, 192\&.168\&.0\&.1; 10\&.0\&.0\-255\&.1\-254
  \-iL <inputfilename>: Input from list of hosts/networks
  \-\-exclude <host1[,host2][,host3],\&.\&.\&.>: Exclude hosts/networks
  \-\-excludefile <exclude_file>: Exclude list from file
SERVICE SPECIFICATION:
  Can pass target specific services in <service>://target (standard) notation or
  using \-p which will be applied to all hosts in non\-standard notation\&.
  Service arguments can be specified to be host\-specific, type of service\-specific
  (\-m) or global (\-g)\&. Ex: ssh://10\&.0\&.0\&.10,at=10,cl=30 \-m ssh:at=50 \-g cd=3000
  Ex2: ncrack \-p ssh,ftp:3500,25 10\&.0\&.0\&.10 scanme\&.nmap\&.org google\&.com:80,ssl
  \-p <service\-list>: services will be applied to all non\-standard notation hosts
  \-m <service>:<options>: options will be applied to all services of this type
  \-g <options>: options will be applied to every service globally
  Misc options:
    ssl: enable SSL over this service
    path: path\-name used in modules like HTTP (\'=\' needs escaping if used)
TIMING AND PERFORMANCE:
  Options which take <time> are in milliseconds, unless you append \'s\'
  (seconds), \'m\' (minutes), or \'h\' (hours) to the value (e\&.g\&. 30m)\&.
  Service\-specific options:
    cl (min connection limit): minimum number of concurrent parallel connections
    CL (max connection limit): maximum number of concurrent parallel connections
    at (authentication tries): authentication attempts per connection
    cd (connection delay): delay <time> between each connection initiation
    cr (connection retries): caps number of service connection attempts
    to (time\-out): maximum cracking <time> for service, regardless of success so far
  \-T<0\-5>: Set timing template (higher is faster)
  \-\-connection\-limit <number>: threshold for total concurrent connections
AUTHENTICATION:
  \-U <filename>: username file
  \-P <filename>: password file
  \-\-passwords\-first: Iterate password list for each username\&. Default is opposite\&.
OUTPUT:
  \-oN/\-oX <file>: Output scan in normal and XML format, respectively, to the given filename\&.
  \-oA <basename>: Output in the two major formats at once
  \-v: Increase verbosity level (use twice or more for greater effect)
  \-d[level]: Set or increase debugging level (Up to 10 is meaningful)
  \-\-log\-errors: Log errors/warnings to the normal\-format output file
  \-\-append\-output: Append to rather than clobber specified output files
MISC:
  \-sL or \-\-list: only list hosts and services
  \-\-datadir <dirname>: Specify custom Ncrack data file location
  \-V: Print version number
  \-h: Print this help summary page\&.
.fi
.if n \{\
.RE
.\}
.\" 
.\" 
.SH "TARGET SPECIFICATION"
.\" target specification
.PP
Everything on the Ncrack command\-line that isn\'t an option (or an option argument) is treated as a target host specification\&. The simplest case is to specify a target IP address or a hostname\&. Note, that you also need to specify a service to crack for the selected targets\&. Ncrack is very flexible in host/service specification\&. While hostnames and IP addresses can be defined with the flexibility that you are probably used to from Nmap, services along with service\-specific options have a unique specification style that enables a combination of features to be taken advantage of\&.
.PP
Sometimes you wish to crack a whole network of adjacent hosts\&. For this, Ncrack supports CIDR\-style
.\" CIDR (Classless Inter-Domain Routing)
addressing\&. You can append /\fInumbits\fR
to an IPv4 address or hostname and Ncrack will try to crack every IP address for which the first numbits are the same as for the reference IP or hostname given\&. For example, 192\&.168\&.10\&.0/24 would send probes to the 256 hosts between 192\&.168\&.10\&.0
11000000 10101000 00001010 00000000) and 192\&.168\&.10\&.255 (binary:
11000000 10101000 00001010 11111111), inclusive\&. 192\&.168\&.10\&.40/24 would crack exactly the same targets\&. Given that the host
scanme\&.nmap\&.org
.\" scanme.nmap.org
is at the IP address 64\&.13\&.134\&.52, the specification scanme\&.nmap\&.org/16 would send probes to the 65,536 IP addresses between 64\&.13\&.0\&.0 and 64\&.13\&.255\&.255\&. The smallest allowed value is /0, which targets the whole Internet\&. The largest value is /32, which targets just the named host or IP address because all address bits are fixed\&.
.\" address ranges
.PP
CIDR notation is short but not always flexible enough\&. For example, you might want to send probes to 192\&.168\&.0\&.0/16 but skip any IPs ending with \&.0 or \&.255 because they may be used as subnet network and broadcast addresses\&. Ncrack supports this through octet range addressing\&. Rather than specify a normal IP address, you can specify a comma\-separated list of numbers or ranges for each octet\&. For example, 192\&.168\&.0\-255\&.1\-254 will skip all addresses in the range that end in \&.0 or \&.255, and 192\&.168\&.3\-5,7\&.1 will target the four addresses 192\&.168\&.3\&.1, 192\&.168\&.4\&.1, 192\&.168\&.5\&.1, and 192\&.168\&.7\&.1\&. Either side of a range may be omitted; the default values are 0 on the left and 255 on the right\&. Using
\-
by itself is the same as 0\-255, but remember to use 0\- in the first octet so the target specification doesn\'t look like a command\-line option\&. Ranges need not be limited to the final octets: the specifier will send probes to all IP addresses on the Internet ending in 13\&.37 This sort of broad sampling can be useful for Internet surveys and research\&.
.PP
Ncrack accepts multiple host specifications on the command line, and they don\'t need to be the same type\&. The command
\fBncrack scanme\&.nmap\&.org 192\&.168\&.0\&.0/8 10\&.0\&.0,1,3\-7\&.\- \-p22\fR
does what you would expect\&.
.PP
While targets are usually specified on the command lines, the following options are also available to control target selection:
.PP
\fB\-iL \fR\fB\fIinputfilename\fR\fR (Input from list) .\" -iL .\" target specification: from list
.RS 4
Reads target specifications from
\fIinputfilename\fR\&. Passing a huge list of hosts is often awkward on the command line, yet it is a common desire\&. For example, you might want to crack a list of very specific servers that have been specified for penetration testing\&. Simply generate the list of hosts to crack and pass that filename to Ncrack as an argument to the
\fB\-iL\fR
option\&. Entries can be in any of the formats accepted by Ncrack on the command line (IP address, hostname, CIDR, octet ranges or Ncrack\'s special host\-service syntax\&. Each entry must be separated by one or more spaces, tabs, or newlines\&. You can specify a hyphen (\-) as the filename if you want Ncrack to read hosts from standard input rather than an actual file\&. Note, however, that if hosts are specified without any service, you will have to also provide services/ports for the targets using the
\fB\-p\fR
option\&.
.RE
.PP
\fB\-\-exclude \fR\fB\fIhost1\fR\fR\fB[, \fIhost2\fR[, \&.\&.\&.]]\fR (Exclude hosts/networks) .\" --exclude .\" excluding targets
.RS 4
Specifies a comma\-separated list of targets to be excluded from the scan even if they are part of the overall network range you specify\&. The list you pass in uses normal Ncrack syntax, so it can include hostnames, CIDR netblocks, octet ranges, etc\&. This can be useful when the network you wish to scan includes untouchable mission\-critical servers, systems that are known to react adversely to heavy load, or subnets administered by other people\&.
.RE
.PP
\fB\-\-excludefile \fR\fB\fIexclude_file\fR\fR\fB \fR (Exclude list from file) .\" --excludefile
.RS 4
This offers the same functionality as the
\fB\-\-exclude\fR
option, except that the excluded targets are provided in a newline, space, or tab delimited
\fIexclude_file\fR
rather than on the command line\&.
.RE
.SH "SERVICE SPECIFICATION"
.\" target specification
.PP
No cracking session can be carried out without a certain service to attack\&. Service specification is one of the most flexible subsystems of Ncrack and collaborates with target\-specification in a way that allows different option combinations to be applied\&.
.SH "OUTPUT"
.\" output formats
.PP
Any security tool is only as useful as the output it generates\&. Complex tests and algorithms are of little value if they aren\'t presented in an organized and comprehensible fashion\&. Of course, no single format can please everyone\&. So Ncrack offers several formats, including the interactive mode for humans to read directly and XML for easy parsing by software\&.
.PP
In addition to offering different output formats, Ncrack provides options for controlling the verbosity of output as well as debugging messages\&. Output types may be sent to standard output or to named files, which Ncrack can append to or clobber\&.
.PP
Ncrack makes output available in three different formats\&. The default is called
interactive output, and it is sent to standard output (stdout)\&. There is also
normal output, which is similar to interactive except that it displays less runtime information and warnings since it is expected to be analyzed after the scan completes rather than interactively\&.
.PP
XML output
is one of the most important output types, as it can be converted to HTML, easily parsed by programs such as Ncrack graphical user interfaces, or imported into databases\&. Currently, XML output hasn\'t been implemented\&.
.PP
While interactive output is the default and has no associated command\-line options, the other two format options use the same syntax\&. They take one argument, which is the filename that results should be stored in\&. Multiple formats may be specified, but each format may only be specified once\&. For example, you may wish to save normal output for your own review while saving XML of the same scan for programmatic analysis\&. You might do this with the options
\fB\-oX myscan\&.xml \-oN myscan\&.ncrack\fR\&. While this chapter uses the simple names like
myscan\&.xml
for brevity, more descriptive names are generally recommended\&. The names chosen are a matter of personal preference\&. A scheme could be using long filenames that incorporate the scan date and a word or two describing the scan, placed in a directory named after the company that is being scanned\&.
.PP
While these options save results to files, Ncrack still prints interactive output to stdout as usual\&. For example, the command
\fBnmap \-oX myscan\&.xml [target]\fR
prints XML to
myscan\&.xml
and fills standard output with the same interactive results it would have printed if
\fB\-oX\fR
wasn\'t specified at all\&. You can change this by passing a hyphen character as the argument to one of the format types\&. This causes Ncrack to deactivate interactive output, and instead print results in the format you specified to the standard output stream\&. So the command
\fBnmap \-oX \- target\fR
will send only XML output to stdout\&. Serious errors may still be printed to the normal error stream, stderr\&.
.PP
Unlike some Ncrack arguments, the space between the logfile option flag (such as
\fB\-oX\fR) and the filename or hyphen is mandatory\&.
.PP
All of these arguments support
\fBstrftime\fR\-like conversions in the filename\&.
%H,
%M,
%S,
%m,
%d,
%y, and
%Y
are all exactly the same as in
\fBstrftime\fR\&.
%T
is the same as
%H%M%S,
%R
is the same as
%H%M, and
%D
is the same as
%m%d%y\&. A
%
followed by any other character just yields that character (%%
gives you a percent symbol)\&. So
\fB\-oX \'scan\-%T\-%D\&.xml\'\fR
will use an XML file in the form of
scan\-144840\-121307\&.xml\&.
.PP
Ncrack also offers options to control scan verbosity and to append to output files rather than clobbering them\&. All of these options are described below\&.
.PP
\fBNcrack Output Formats\fR
.PP
\fB\-oN \fR\fB\fIfilespec\fR\fR (normal output) .\" -oN .\" normal output
.RS 4
Requests that
normal output
be directed to the given filename\&. As discussed above, this differs slightly from
interactive output\&.
.RE
.PP
\fB\-oX \fR\fB\fIfilespec\fR\fR (XML output) .\" -oX .\" XML output
.RS 4
Requests that
XML output
be directed to the given filename\&. Currently this is not implemented\&.
.RE
.PP
\fB\-oA \fR\fB\fIbasename\fR\fR (Output to all formats) .\" -oA
.RS 4
As a convenience, you may specify
\fB\-oA \fR\fB\fIbasename\fR\fR
to store scan results in normal and XML formats at once\&. They are stored in
\fIbasename\fR\&.ncrack, and
\fIbasename\fR\&.xml
respectively\&. As with most programs, you can prefix the filenames with a directory path, such as
~/ncracklogs/foocorp/
on Unix or
c:\ehacking\esco
on Windows\&.
.RE
.PP
\fBVerbosity and debugging options\fR
.PP
\fB\-v\fR (Increase verbosity level) .\" -v .\" verbosity
.RS 4
Increases the verbosity level, causing Ncrack to print more information about the scan in progress\&. Credentials are shown as they are found and more statistical information is printed in the end\&. Use it twice or more for even greater verbosity\&.
.\" -v: giving more than once
.RE
.PP
\fB\-d [level]\fR (Increase or set debugging level) .\" -d .\" debugging
.RS 4
When even verbose mode doesn\'t provide sufficient data for you, debugging is available to flood you with much more! As with the verbosity option (\fB\-v\fR), debugging is enabled with a command\-line flag (\fB\-d\fR) and the debug level can be increased by specifying it multiple times\&. Alternatively, you can set a debug level by giving an argument to
\fB\-d\fR\&. For example,
\fB\-d10\fR
sets level ten\&. That is the highest effective level and will produce thousands of lines, unless your cracking session is going really slow\&.
.sp
Debugging output is useful when a bug is suspected in Ncrack, or if you are simply confused as to what Ncrack is doing and why\&. As this feature is mostly intended for developers, debug lines aren\'t always self\-explanatory\&. If you don\'t understand a line, your only recourses are to ignore it, look it up in the source code, or request help from the development list (nmap\-dev)\&. Some lines are self explanatory, but the messages become more obscure as the debug level is increased\&.
.RE
.PP
\fB\-\-log\-errors\fR (Log errors/warnings to normal mode output file) .\" --log-errors
.RS 4
Warnings and errors printed by Ncrack usually go only to the screen (interactive output), leaving any normal\-format output files (usually specified with
\fB\-oN\fR) uncluttered\&. When you do want to see those messages in the normal output file you specified, add this option\&. It is useful when you aren\'t watching the interactive output or when you want to record errors while debugging a problem\&. The error and warning messages will still appear in interactive mode too\&. This won\'t work for most errors related to bad command\-line arguments because Ncrack may not have initialized its output files yet\&.
.sp
An alternative to
\fB\-\-log\-errors\fR
is redirecting interactive output (including the standard error stream) to a file\&. Most Unix shells make this approach easy, though it can be difficult on Windows\&.
.RE
.PP
\fBMiscellaneous output options\fR
.PP
\fB\-\-append\-output\fR (Append to rather than clobber output files) .\" --append-output
.RS 4
When you specify a filename to an output format flag such as
\fB\-oX\fR
or
\fB\-oN\fR, that file is overwritten by default\&. If you prefer to keep the existing content of the file and append the new results, specify the
\fB\-\-append\-output\fR
option\&. All output filenames specified in that Ncrack execution will then be appended to rather than clobbered\&. This doesn\'t work well for XML (\fB\-oX\fR) scan data as the resultant file generally won\'t parse properly until you fix it up by hand\&.
.RE
.SH "MISCELLANEOUS OPTIONS"
.PP
This section describes some important (and not\-so\-important) options that don\'t really fit anywhere else\&.
.PP
\fB\-\-datadir \fR\fB\fIdirectoryname\fR\fR (Specify custom Ncrack data file location) .\" --datadir
.RS 4
Ncrack needs a file called
ncrack\-services
to load a lookup\-table of supported services/ports\&. This file shouldn\'t be changed, unless you know what you are doing (e\&.g extending Ncrack for additional modules)\&. In addition, Ncrack is shipped with various username and password lists, some of which are used by default in case the user doesn\'t specify ones of his own\&. All these files are normally copied during the installation procedure to a directory such as /usr/share/ncrack or /usr/local/share/ncrack \&. Using the
\fB\-\-datadir\fR
option, will force Ncrack to start searching for these files in specified directory\&. If the files aren\'t found, then it will continue searching in the directory specified by the NCRACKDIR environmental variable
\fBNCRACKDIR\fR
(if it is defined)\&. Next comes
~/\&.ncrack
directory for real and effective UIDs (POSIX systems only) or location of the Ncrack executable (Win32 only), and then a compiled\-in location such as
/usr/local/share/ncrack
or
/usr/share/ncrack\&. As a last resort, Ncrack will look in the current directory\&.
.RE
.PP
\fB\-V\fR; \fB\-\-version\fR (Print version number) .\" -V .\" --version
.RS 4
Prints the Ncrack version number and exits\&.
.RE
.PP
\fB\-h\fR; \fB\-\-help\fR (Print help summary page) .\" -h .\" --help
.RS 4
Prints a short help screen with the most common command flags\&. Running Ncrack without any arguments does the same thing\&.
.RE
.SH "RUNTIME INTERACTION"
.PP
During the execution of Ncrack, all key presses are captured\&. This allows you to interact with the program without aborting and restarting it\&. Certain special keys will change options, while any other keys will print out a status message telling you about the scan\&. The convention is that
\fIlowercase letters increase\fR
the amount of printing, and
\fIuppercase letters decrease\fR
the printing\&. You may also press \(oq\fI?\fR\(cq for help\&.
.PP
\fBv\fR / \fBV\fR
.RS 4
Increase / decrease the verbosity level
.RE
.PP
\fBd\fR / \fBD\fR
.RS 4
Increase / decrease the debugging Level
.RE
.PP
\fB?\fR
.RS 4
Print a runtime interaction help screen
.RE
.PP
Anything else
.RS 4
Print out a status message like this:
.sp
Stats: 0:00:20 elapsed; 0 services completed (1 total)
.sp
Rate: 6\&.26; Found: 1; About 13\&.27% done; ETC: 21:06 (0:02:17 remaining)
.RE
.SH "BUGS"
.\" bugs, reporting
.PP
Like its authors, Ncrack isn\'t perfect\&. But you can help make it better by sending bug reports or even writing patches\&. If Ncrack doesn\'t behave the way you expect, first upgrade to the latest version available from
\m[blue]\fB\%http://ncrack.org\fR\m[]\&. If the problem persists, do some research to determine whether it has already been discovered and addressed\&. Try searching for the error message on our search page at
\m[blue]\fB\%http://insecure.org/search.html\fR\m[]
or at Google\&. Also try browsing the
nmap\-dev
archives at
\m[blue]\fB\%http://seclists.org/\fR\m[]
\&.
.\" nmap-dev mailing list
Read this full manual page as well\&. If nothing comes of this, mail a bug report to
nmap\-dev@insecure\&.org
\&. Please include everything you have learned about the problem, as well as what version of Ncrack you are running and what operating system version it is running on\&. Problem reports and Ncrack usage questions sent to
nmap\-dev@insecure\&.org
are far more likely to be answered than those sent to Fyodor directly\&. If you subscribe to the nmap\-dev list before posting, your message will bypass moderation and get through more quickly\&. Subscribe at
\m[blue]\fB\%http://cgi.insecure.org/mailman/listinfo/nmap-dev\fR\m[]
\&.
.PP
Code patches to fix bugs are even better than bug reports\&. Basic instructions for creating patch files with your changes are available at
\m[blue]\fB\%http://nmap.org/data/HACKING\fR\m[]
\&. Patches may be sent to
nmap\-dev
(recommended) or to Fyodor directly\&.
.SH "AUTHORS"
.PP
ithilgore
ithilgore\&.ryu\&.l@gmail\&.com
(\m[blue]\fB\%http://sock-raw.org\fR\m[])
.PP
Fyodor
fyodor@insecure\&.org
(\m[blue]\fB\%http://insecure.org\fR\m[])
